version: '3.4'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: metrics-clickhouse
    restart: unless-stopped
    environment:
      - CLICKHOUSE_USER=test
      - CLICKHOUSE_PASSWORD=test
      - CLICKHOUSE_DB=metrics
    ports:
      - "38100:8123"