version: '3.4'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: metrics-clickhouse
    restart: unless-stopped
    environment:
      - CLICKHOUSE_USER=test
      - CLICKHOUSE_PASSWORD=test
      - CLICKHOUSE_DB=metrics
    ports:
      - "8123:8123"
      - "9000:9000"

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: metrics-rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"