version: '3.4'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: metrics-clickhouse
    restart: unless-stopped
    environment:
      - CLICKHOUSE_USER=test
      - CLICKHOUSE_PASSWORD=test
      - CLICKHOUSE_DB=metrics
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./configurations/named_collections.xml:/etc/clickhouse-server/config.d/named_collections.xml
      - ./configurations/custom_users.xml:/etc/clickhouse-server/users.d/custom_users.xml

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: metrics-rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"